use('velu')
db.exam.insertMany([
    {
        stuid:101,
        semester:1,
        subjects:{
                softcom:{
                doe:'24-09-2023',
                sem:98,
                int:28
            },
            linux:{
                doe:'25-09-2023',
                sem:58,
                int:28
            },
             DataEngineering:{
                doe:'26-09-2023',
                sem:59,
                int:30
            },
            Python:{
                doe:'28-09-2023',
                sem:70,
                int:29
            }
        }
    },{
        stuid:102,
        semester:1,
        subjects:{
                softcom:{
                doe:'24-09-2023',
                sem:68,
                int:28
            },
            linux:{
                doe:'25-09-2023',
                sem:70,
                int:28
            },
             DataEngineering:{
                doe:'26-09-2023',
                sem:59,
                int:30
            },
            Python:{
                doe:'28-09-2023',
                sem:70,
                int:29
            }
        }
    },{
        stuid:103,
        semester:1,
        subjects:{
                softcom:{
                doe:'24-09-2023',
                sem:55,
                int:28
            },
            linux:{
                doe:'25-09-2023',
                sem:70,
                int:28
            },
             DataEngineering:{
                doe:'26-09-2023',
                sem:59,
                int:30
            },
            Python:{
                doe:'28-09-2023',
                sem:70,
                int:29
            }
        }
    },{
        stuid:104,
        semester:1,
        subjects:{
                softcom:{
                doe:'24-09-2023',
                sem:60,
                int:28
            },
            linux:{
                doe:'25-09-2023',
                sem:69,
                int:28
            },
             DataEngineering:{
                doe:'26-09-2023',
                sem:59,
                int:30
            },
            Python:{
                doe:'28-09-2023',
                sem:70,
                int:29
            }
        }
    }
])